[package]
name = "fahapi"
version = "0.1.0"
authors = ["Makoto <makoto@emurasoft.com>"]
edition = "2018"

[features]
all-tests = [] # Run tests that will modify your FAH settings

[dependencies]
snafu = "0.6.8"
bytes = "0.5"
lazy_static = "1.4.0"
regex = "1"