name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sed -i -e "s/version = \"0.0.0\"/version = \"${GITHUB_REF#refs/tags/}\"/g" Cargo.toml
      - run: cargo login ${{ secrets.CARGO_TOKEN }}
      - run: cargo publish --allow-dirty