name: Test
on:
  push:
    branches:
      - '*'
      - api
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: 	ubuntu-20.04
    steps:
      - run: wget https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v7.6/fahclient_7.6.13_amd64.deb
      - run: sudo dpkg -i fahclient_7.6.13_amd64.deb
      - run: FAHClient --send-command pause
      - uses: actions/checkout@v2
      - run: cargo test --all-features
      - run: cargo fmt -- --check