name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
        image: emurasoft/rust-fahapi-ci:2
    steps:
      - run: /etc/init.d/FAHClient start > /dev/null || true
      - run: sleep 0.5
      - run: FAHClient --send-command pause
      - uses: actions/checkout@v2
      - run: RUST_BACKTRACE=full cargo test --all-features -- --nocapture
      - run: cargo doc --all-features
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo fmt -- --check