name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: 	ubuntu-20.04
    container:
        image: emurasoft/rust-fahapi-ci:0
    steps:
      - run: /etc/init.d/FAHClient start > /dev/null || true
      - run: sleep 0.5
      - run: FAHClient --send-command pause
      - uses: actions/checkout@v2
      - run: cargo test --all-features
      - run: cargo fmt -- --check